name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o nba_api-linux -v .

      - name: Test
        run: go test -v ./...
